image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  SPRING_PROFILES_ACTIVE: gitlab-ci
  MAVEN_OPTS: -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2

stages:
  - build-test

maven-build:
  image: maven:3-jdk-8-alpine
  stage: build-test
  script: 
    - cd projects
    - "mvn verify -B"
      