@startuml
skinparam dpi 200

title Asynchronous communication

actor PSIproduct
boundary AsyncGateway as Async <<JMS>>
boundary Gateway
boundary Engine as Engine

autonumber
PSIproduct -\ Async: queue{CalculationDefinition}
Async -\ Gateway: queue(CalculationDefinition)
Gateway -> Engine: call
Engine -> Engine
Engine -> Gateway: {calculationResult}
Gateway -\ Async: queue{calculationResult}
Async -\ PSIproduct: queue{calculationResult}

@enduml