@startuml
skinparam dpi 200

title Synchronous communication

actor PSIproduct
boundary SyncGateway as Sync <<WebService>> <<MethodCall>>
boundary Gateway
boundary Engine as Engine

autonumber
activate PSIproduct
PSIproduct -> Sync: execute{CalculationDefinition}
activate Sync
Sync -> Gateway: execute(CalculationDefinition)
Gateway -> Engine: call
Engine -> Engine
Engine -> Gateway: {calculationResult}
Gateway -> Sync: {calculationResult}
deactivate Sync
Sync -> PSIproduct: {calculationResult}
deactivate PSIproduct

@enduml