@startuml

title Definition called with data source definition

actor PSIproduct
boundary Gateway
boundary DataRepository as Repo
boundary Engine as Engine

autonumber
PSIproduct -> Gateway: execute(CalculationDefinition, dataSourceDefinition)
Gateway -> Repo: fetch(dataSourceDefinition)
Repo -> Gateway: data
Gateway -> Engine: call(data)
Engine -> Engine
Engine -> Gateway: {calculationResult}
Gateway -> PSIproduct: {calculationResult}

@enduml