@startuml
skinparam dpi 200
skinparam backgroundColor transparent

title Definition of mixed scenario

actor PSIproduct
boundary Gateway as jms <<JMS>>
boundary Gateway as ws <<WebService>>
database AuxDB as auxdb
boundary Engine as Engine

' TODO what with scenarios when there is no data passed but for eg. TS is returned?

autonumber
PSIproduct ->jms: execute(CalculationDefinition)
jms -> Engine: call(CalculationDefinition)
Engine -> Engine: calculation
Engine -> auxdb: {calculationResult}
PSIproduct -> ws: getResult
ws -> auxdb
auxdb -> ws
ws -> PSIproduct: {calculationResult}

@enduml