@startuml
skinparam dpi 200
skinparam backgroundColor transparent

title PSImarket Context

actor User
actor BusinessAnalyst as BA
component PSIProduct as PSI <<PSImarket>>
component RStudio as rstdio
component AAAS as 3as
component Engine as engine <<R>>

User <--> PSI
BA <--> rstdio
PSI <--> 3as
rstdio <--> 3as
3as <--> engine

@enduml