@startuml
skinparam dpi 200
skinparam backgroundColor transparent

title AI OR AE Containers

actor User
package {
    component PSIProduct as PSI
    database DB
}
component AAAS as 3as
cloud {
  component Engines as engine
}

User <--> PSI
PSI <--> 3as
3as <--> engine

@enduml