@startuml
skinparam dpi 200
skinparam backgroundColor transparent

title EDM/PSImarket Containers

actor User
actor BusinessAnalyst as BA
package {
    database TSDB as tsdb
    component PSIProduct as PSI <<PSImarket>>
    component AAAS as 3as
}
component RStudio as rstdio
database ScriptsRepository as scripts <<Git>>
cloud {
    component Engines as engine <<R>>
}
database ModelsRepository as models

User <--> PSI
BA <--> rstdio
rstdio <--> scripts : git
PSI <--> tsdb
PSI <--> 3as : method calls
rstdio <--> 3as : Rserve/GPB
3as <--> engine : Rserve/GPB
engine <-right-> scripts : git
engine <--> models

@enduml